name: first
on:
   push

jobs:
    runcommands:
         runs-on: ubuntu-latest

         steps:
             - name: Checkout the code
               uses: actions/checkout@v4

             - name: Run the single command
               run: echo "Hello World"

             - name: Run the multiple commands
               run: |

                  echo "This is multiline cmd"
                  echo "Hello this si important"


