name: first
on:
   push

jobs:
    runcommands:
         runs-on: ubuntu-latest

         steps:
             - name: Checkout the code
               uses: actions/checkout@v4

             - name: Run the single command
               run: echo "Hello World"

             - name: Run the multiple commands
               run: |

                  echo "This is multiline cmd"
                  exit 1

    runcommandsagain:
         runs-on: ubuntu-latest
         needs: [runcommands]

         steps:
             - name: Checkout the code
               uses: actions/checkout@v4

             - name: Run the single command
               run: echo "Github Action_workflows"

             - name: Run the multiple commands
               run: |

                  echo "This is multiline cmd"
                  echo "Hello...working with github actions"



